name: fetchx
description: Make http requests easily
version: 0.0.1
homepage: https://github.com/bryanbill/fetch

environment:
  sdk: '>=2.16.2 <3.0.0'


# dependencies:
#   path: ^1.8.0

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0
